# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

K_sob_cpp <- function(s, t) {
    .Call('_rkhscovfun_K_sob_cpp', PACKAGE = 'rkhscovfun', s, t)
}

getK <- function(t) {
    .Call('_rkhscovfun_getK', PACKAGE = 'rkhscovfun', t)
}

getM <- function(t, k = 150L, p = 20L, tol = 1e-8) {
    .Call('_rkhscovfun_getM', PACKAGE = 'rkhscovfun', t, k, p, tol)
}

svec_cpp <- function(B) {
    .Call('_rkhscovfun_svec_cpp', PACKAGE = 'rkhscovfun', B)
}

Qlossprep_cpp <- function(Xs, Ms, include) {
    .Call('_rkhscovfun_Qlossprep_cpp', PACKAGE = 'rkhscovfun', Xs, Ms, include)
}

testQloss <- function(Bv, RR, RQv, c) {
    .Call('_rkhscovfun_testQloss', PACKAGE = 'rkhscovfun', Bv, RR, RQv, c)
}

prox_trace_hs <- function(Bv, s1, s2, weight, r, max_rank, pos = TRUE) {
    .Call('_rkhscovfun_prox_trace_hs', PACKAGE = 'rkhscovfun', Bv, s1, s2, weight, r, max_rank, pos)
}

prox <- function(Bv, s1, s2, weight, r, max_rank, pos = TRUE) {
    .Call('_rkhscovfun_prox', PACKAGE = 'rkhscovfun', Bv, s1, s2, weight, r, max_rank, pos)
}

rkhscov_pg_cpp <- function(RR, RQv, c, lam, gam, B0v, weight, L = 1.0, eta = 2.0, alpha = 0.9, maxit = 10000L, traceit = TRUE, tol = 1e-8, max_rank = -1L, pos = TRUE, variant = 2L, cond = 2L) {
    .Call('_rkhscovfun_rkhscov_pg_cpp', PACKAGE = 'rkhscovfun', RR, RQv, c, lam, gam, B0v, weight, L, eta, alpha, maxit, traceit, tol, max_rank, pos, variant, cond)
}

start_lambda <- function(RR, RQv, c, weight, gam, pos = TRUE, rtol = 1e-4) {
    .Call('_rkhscovfun_start_lambda', PACKAGE = 'rkhscovfun', RR, RQv, c, weight, gam, pos, rtol)
}

sumvaliderr <- function(RR, RQv, c, Bv) {
    .Call('_rkhscovfun_sumvaliderr', PACKAGE = 'rkhscovfun', RR, RQv, c, Bv)
}

rkhscov_pg_cvj_cpp <- function(Xs, Ms, traingroup, testgroup, lams, gam, B0v, weight, L = 1.0, eta = 2.0, alpha = 0.9, maxit = 1000L, traceit = TRUE, tol = 1e-8, max_rank = -1L, pos = TRUE, variant = 2L, cond = 2L) {
    .Call('_rkhscovfun_rkhscov_pg_cvj_cpp', PACKAGE = 'rkhscovfun', Xs, Ms, traingroup, testgroup, lams, gam, B0v, weight, L, eta, alpha, maxit, traceit, tol, max_rank, pos, variant, cond)
}

